from datetime import date, timedelta
import uuid
from sqlalchemy.orm import Session

from backend.app.models.billing_cycle import BillingCycle
from backend.app.schemas.billing_cycle import BillingCycleCreate
from backend.app.models.subscription import Subscription
from backend.app.models.plan import Plan
from backend.app.models.invoice import Invoice


def create_billing_cycle(db: Session, billing_cycle: BillingCycleCreate):
    db_billing_cycle = BillingCycle(**billing_cycle.model_dump())
    db.add(db_billing_cycle)
    db.commit()
    db.refresh(db_billing_cycle)
    return db_billing_cycle


def get_all_billing_cycles(db: Session):
    return db.query(BillingCycle).all()


def get_billing_cycle(db: Session, billing_cycle_id: int):
    return (
        db.query(BillingCycle)
        .filter(BillingCycle.id == billing_cycle_id)
        .first()
    )


def delete_billing_cycle(db: Session, billing_cycle_id: int):
    billing_cycle = (
        db.query(BillingCycle)
        .filter(BillingCycle.id == billing_cycle_id)
        .first()
    )

    if billing_cycle:
        db.delete(billing_cycle)
        db.commit()

    return billing_cycle


from datetime import date, timedelta
import uuid
from sqlalchemy.orm import Session

from backend.app.models.subscription import Subscription
from backend.app.models.plan import Plan
from backend.app.models.invoice import Invoice


def generate_due_invoices(db: Session):
    today = date.today()

    processed_subscriptions = 0
    generated_invoices = 0

    active_subscriptions = (
        db.query(Subscription)
        .filter(
            Subscription.status == "ACTIVE",
            Subscription.is_deleted == False,
            Subscription.next_billing_date <= today
        )
        .all()
    )

    for subscription in active_subscriptions:

        processed_subscriptions += 1

        plan = (
            db.query(Plan)
            .filter(
                Plan.id == subscription.plan_id,
                Plan.status == "ACTIVE",
                Plan.is_deleted == False
            )
            .first()
        )

        if not plan:
            continue

        invoice = Invoice(
            subscription_id=subscription.id,
            invoice_number=f"INV-{uuid.uuid4().hex[:8].upper()}",
            amount=plan.price,
            issue_date=today,
            due_date=today + timedelta(days=7),
            status="PENDING",
            payment_date=None,
            remarks="Automatically generated by billing cycle"
        )

        db.add(invoice)

        generated_invoices += 1

        if plan.billing_cycle.upper() == "MONTHLY":
            subscription.next_billing_date = today + timedelta(days=30)

        elif plan.billing_cycle.upper() == "YEARLY":
            subscription.next_billing_date = today + timedelta(days=365)

        db.add(subscription)

    db.commit()

    return {
        "message": "Billing cycle executed successfully.",
        "processed_subscriptions": processed_subscriptions,
        "generated_invoices": generated_invoices
    }