import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Paper,
  Grid,
  Divider,
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableCell,
  Button,
  Chip,
  Alert,
} from '@mui/material';
import ArrowBackIcon from '@mui/icons-material/ArrowBack';
import CreditCardIcon from '@mui/icons-material/CreditCard';
import DownloadIcon from '@mui/icons-material/Download';
import { useParams, useNavigate } from 'react-router-dom';

import { invoiceService } from '../../services/invoiceService';
import StatusBadge from '../../components/common/StatusBadge';
import { formatDate, formatCurrency } from '../../utils/formatters';

const InvoiceDetailsPage = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  const [invoice, setInvoice] = useState(null);
  const [lineItems, setLineItems] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    const fetchInvoice = async () => {
      setLoading(true);
      try {
        const data = await invoiceService.getById(id);
        setInvoice(data);
        if (data.line_items && data.line_items.length > 0) {
          setLineItems(data.line_items);
        } else {
          const items = await invoiceService.getLineItems(id);
          setLineItems(items);
        }
      } catch {
        // error
      } finally {
        setLoading(false);
      }
    };
    fetchInvoice();
  }, [id]);

  if (loading) {
    return (
      <Box sx={{ p: 4 }}>
        <Typography variant="h6">Loading Invoice Details...</Typography>
      </Box>
    );
  }

  if (!invoice) {
    return (
      <Alert severity="error" sx={{ my: 4 }}>
        Invoice record not found.
      </Alert>
    );
  }

  return (
    <Box sx={{ maxWidth: 900, mx: 'auto' }}>
      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 3 }}>
        <Button
          startIcon={<ArrowBackIcon />}
          onClick={() => navigate('/invoices')}
          sx={{ textTransform: 'none' }}
        >
          Back to Invoices
        </Button>
        <Box sx={{ display: 'flex', gap: 2 }}>
          <Button
            variant="contained"
            color="success"
            startIcon={<DownloadIcon />}
            onClick={() => window.open(invoiceService.downloadPdfUrl(invoice.id), '_blank')}
            sx={{ textTransform: 'none', fontWeight: 800 }}
          >
            Download ReportLab PDF
          </Button>
          <Button
            variant="outlined"
            startIcon={<DownloadIcon />}
            onClick={() => window.open(invoiceService.downloadHtmlUrl(invoice.id), '_blank')}
            sx={{ textTransform: 'none', fontWeight: 700 }}
          >
            Print / HTML Statement
          </Button>
          {(invoice.status === 'PENDING' || invoice.status === 'pending' || invoice.status === 'UNPAID') && (
            <Button
              variant="contained"
              color="primary"
              startIcon={<CreditCardIcon />}
              onClick={() => navigate('/payments/process', { state: { subscription_id: invoice.subscription_id, invoice_id: invoice.id, amount: invoice.amount, invoice_number: invoice.invoice_number } })}
            >
              Process Payment Now
            </Button>
          )}
        </Box>
      </Box>

      <Paper elevation={2} sx={{ p: 5, borderRadius: 3, border: '1px solid #e2e8f0', bgcolor: '#ffffff' }}>
        <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', mb: 4 }}>
          <Box>
            <Typography variant="h4" fontWeight={800} color="primary" gutterBottom>
              TAX INVOICE
            </Typography>
            <Typography variant="subtitle1" fontWeight={700} color="text.primary">
              {invoice.invoice_number}
            </Typography>
            <Typography variant="caption" color="text.secondary" display="block">
              Generated by Nexora Billing Engine
            </Typography>
          </Box>
          <Box sx={{ textAlign: 'right' }}>
            <StatusBadge status={invoice.status} />
            <Typography variant="caption" color="text.secondary" display="block" sx={{ mt: 1 }}>
              Issue Date: {formatDate(invoice.issue_date)}
            </Typography>
            <Typography variant="caption" color="text.secondary" display="block">
              Due Date: {formatDate(invoice.due_date)}
            </Typography>
            {invoice.payment_date && (
              <Typography variant="caption" color="success.main" display="block" fontWeight={700}>
                Payment Date: {formatDate(invoice.payment_date)}
              </Typography>
            )}
          </Box>
        </Box>

        <Divider sx={{ mb: 4 }} />

        <Grid container spacing={4} sx={{ mb: 4 }}>
          <Grid item xs={6}>
            <Typography variant="caption" fontWeight={700} color="text.secondary" sx={{ textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              Billed Subscriber
            </Typography>
            <Typography variant="subtitle1" fontWeight={700} sx={{ mt: 0.5 }}>
              {invoice.customer_name || invoice.customerName || 'Customer Account'}
            </Typography>
            {invoice.customer_email && (
              <Typography variant="body2" color="text.secondary">
                {invoice.customer_email}
              </Typography>
            )}
            <Typography variant="body2" color="text.secondary">
              Subscription ID: #{invoice.subscription_id} {invoice.plan_name ? `(${invoice.plan_name})` : ''}
            </Typography>
          </Grid>

          <Grid item xs={6}>
            <Typography variant="caption" fontWeight={700} color="text.secondary" sx={{ textTransform: 'uppercase', letterSpacing: '0.05em' }}>
              Invoice Status & Remarks
            </Typography>
            <Typography variant="body1" fontWeight={600} sx={{ mt: 0.5 }}>
              {invoice.remarks || 'Standard billing cycle invoice'}
            </Typography>
          </Grid>
        </Grid>

        {/* Plan Transition Summary Banner if Upgrade or Downgrade */}
        {invoice.remarks && (invoice.remarks.includes('Upgrade') || invoice.remarks.includes('Downgrade') || invoice.billing_direction === 'PLATFORM_REFUNDS_CUSTOMER' || invoice.refund_amount > 0) && (
          <Paper
            elevation={0}
            sx={{
              p: 3,
              mb: 4,
              borderRadius: 2,
              bgcolor: (invoice.billing_direction === 'PLATFORM_REFUNDS_CUSTOMER' || invoice.refund_amount > 0) ? '#f0fdf4' : '#f0f9ff',
              border: `1px solid ${(invoice.billing_direction === 'PLATFORM_REFUNDS_CUSTOMER' || invoice.refund_amount > 0) ? '#bbf7d0' : '#bae6fd'}`,
            }}
          >
            <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1.5 }}>
              <Typography variant="subtitle1" fontWeight={800} color={(invoice.billing_direction === 'PLATFORM_REFUNDS_CUSTOMER' || invoice.refund_amount > 0) ? '#15803d' : '#0369a1'}>
                {(invoice.billing_direction === 'PLATFORM_REFUNDS_CUSTOMER' || invoice.refund_amount > 0) ? '💵 PLATFORM REFUND / CREDIT TO CUSTOMER' : '⚡ CUSTOMER PAYABLE UPGRADE CHARGE'}
              </Typography>
              <Chip
                label={(invoice.billing_direction === 'PLATFORM_REFUNDS_CUSTOMER' || invoice.refund_amount > 0) ? 'PLATFORM REFUNDS CUSTOMER' : 'CUSTOMER PAYS US'}
                color={(invoice.billing_direction === 'PLATFORM_REFUNDS_CUSTOMER' || invoice.refund_amount > 0) ? 'success' : 'primary'}
                size="small"
                sx={{ fontWeight: 800 }}
              />
            </Box>
            <Grid container spacing={2}>
              <Grid item xs={6}>
                <Typography variant="caption" color="text.secondary" display="block">
                  Proration Summary:
                </Typography>
                <Typography variant="body2" fontWeight={700}>
                  {invoice.remarks}
                </Typography>
              </Grid>
              <Grid item xs={6}>
                {(invoice.billing_direction === 'PLATFORM_REFUNDS_CUSTOMER' || invoice.refund_amount > 0) ? (
                  <Box>
                    <Typography variant="caption" color="success.main" fontWeight={700} display="block">
                      Amount We Refund / Credit Back to Customer:
                    </Typography>
                    <Typography variant="h5" fontWeight={900} color="success.main">
                      {formatCurrency(invoice.refund_amount || 0)} (Customer Bill: ₹0.00)
                    </Typography>
                  </Box>
                ) : (
                  <Box>
                    <Typography variant="caption" color="primary.main" fontWeight={700} display="block">
                      Additional Amount Customer Pays Us:
                    </Typography>
                    <Typography variant="h5" fontWeight={900} color="primary.main">
                      {formatCurrency(invoice.amount)}
                    </Typography>
                  </Box>
                )}
              </Grid>
            </Grid>
          </Paper>
        )}

        <Typography variant="h6" fontWeight={700} sx={{ mb: 1.5 }}>
          Itemized Line Items
        </Typography>

        <Table sx={{ border: '1px solid #e2e8f0', borderRadius: 2, mb: 4 }}>
          <TableHead sx={{ bgcolor: '#f8fafc' }}>
            <TableRow>
              <TableCell><strong>Description</strong></TableCell>
              <TableCell align="center"><strong>Line Item Type</strong></TableCell>
              <TableCell align="right"><strong>Amount (₹)</strong></TableCell>
            </TableRow>
          </TableHead>
          <TableBody>
            {lineItems.length > 0 ? (
              lineItems.map((item, idx) => (
                <TableRow key={item.id || idx}>
                  <TableCell>{item.description}</TableCell>
                  <TableCell align="center">
                    <Chip
                      label={(item.item_type || 'PLAN_FEE').replace('_', ' ')}
                      size="small"
                      color={String(item.item_type).toLowerCase().includes('credit') ? 'success' : String(item.item_type).toLowerCase().includes('debit') ? 'primary' : 'default'}
                      sx={{ textTransform: 'capitalize', fontWeight: 600, fontSize: '0.7rem' }}
                    />
                  </TableCell>
                  <TableCell align="right" sx={{ fontWeight: 600, color: item.amount < 0 ? 'success.main' : 'text.primary' }}>
                    {formatCurrency(item.amount)}
                  </TableCell>
                </TableRow>
              ))
            ) : (
              <TableRow>
                <TableCell>Subscription Plan Base Fee</TableCell>
                <TableCell align="center">
                  <Chip label="PLAN FEE" size="small" sx={{ fontWeight: 600, fontSize: '0.7rem' }} />
                </TableCell>
                <TableCell align="right" sx={{ fontWeight: 600 }}>
                  {formatCurrency(invoice.amount)}
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>

        <Box sx={{ width: '100%', display: 'flex', justifyContent: 'flex-end' }}>
          <Box sx={{ width: 380, p: 2.5, bgcolor: '#f8fafc', borderRadius: 2, border: '1px solid #e2e8f0' }}>
            {lineItems.find((i) => i.item_type === 'PLAN_FEE') && (
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
                <Typography variant="body2" color="text.secondary">Target Base Plan Price:</Typography>
                <Typography variant="body2" fontWeight={700}>
                  {formatCurrency(lineItems.find((i) => i.item_type === 'PLAN_FEE').amount)}
                </Typography>
              </Box>
            )}

            {lineItems.find((i) => i.item_type === 'PRORATION_CREDIT' && i.amount < 0 && !i.description.includes('Dispatched')) && (
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
                <Typography variant="body2" color="success.main" fontWeight={600}>Proration Credit (Unused Period):</Typography>
                <Typography variant="body2" fontWeight={700} color="success.main">
                  {formatCurrency(lineItems.find((i) => i.item_type === 'PRORATION_CREDIT' && i.amount < 0 && !i.description.includes('Dispatched')).amount)}
                </Typography>
              </Box>
            )}

            {lineItems.find((i) => i.item_type === 'PRORATION_DEBIT' && i.amount > 0) && (
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
                <Typography variant="body2" color="primary.main" fontWeight={600}>Proration Debit (Upgrade Charge):</Typography>
                <Typography variant="body2" fontWeight={700} color="primary.main">
                  + {formatCurrency(lineItems.find((i) => i.item_type === 'PRORATION_DEBIT' && i.amount > 0).amount)}
                </Typography>
              </Box>
            )}

            {lineItems.find((i) => i.item_type === 'USAGE_CHARGE') && (
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
                <Typography variant="body2" color="info.main" fontWeight={600}>Metered Usage Charges:</Typography>
                <Typography variant="body2" fontWeight={700} color="info.main">
                  + {formatCurrency(lineItems.find((i) => i.item_type === 'USAGE_CHARGE').amount)}
                </Typography>
              </Box>
            )}

            {lineItems.find((i) => i.item_type === 'DISCOUNT') && (
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
                <Typography variant="body2" color="warning.main" fontWeight={600}>Promotional Discount:</Typography>
                <Typography variant="body2" fontWeight={700} color="warning.main">
                  {formatCurrency(lineItems.find((i) => i.item_type === 'DISCOUNT').amount)}
                </Typography>
              </Box>
            )}

            {invoice.tax_amount > 0 && (
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 1 }}>
                <Typography variant="body2" color="text.secondary">Tax (18% GST):</Typography>
                <Typography variant="body2" fontWeight={700}>{formatCurrency(invoice.tax_amount)}</Typography>
              </Box>
            )}

            <Divider sx={{ my: 1.5 }} />

            {invoice.billing_direction === 'PLATFORM_REFUNDS_CUSTOMER' || invoice.refund_amount > 0 ? (
              <Box>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 0.5 }}>
                  <Typography variant="body2" color="text.secondary">Customer Payable Bill:</Typography>
                  <Typography variant="body2" fontWeight={700} color="text.secondary">₹0.00</Typography>
                </Box>
                <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <Typography variant="subtitle1" fontWeight={800} color="success.main">Net Refund / Credit:</Typography>
                  <Typography variant="h5" fontWeight={900} color="success.main">{formatCurrency(invoice.refund_amount || 0)}</Typography>
                </Box>
              </Box>
            ) : (
              <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                <Typography variant="h6" fontWeight={800}>Grand Total Payable:</Typography>
                <Typography variant="h5" fontWeight={900} color="primary">{formatCurrency(invoice.amount)}</Typography>
              </Box>
            )}
          </Box>
        </Box>
      </Paper>
    </Box>
  );
};

export default InvoiceDetailsPage;
